export const options = {
  mode: "javascript",
  theme: "material",
  lineNumbers: true,
  lineWrapping: true,
  indentUnit: 2,
  tabSize: 2,
  indentWithTabs: true,
  autofocus: true,
  autoCloseTags: true,
  autoCloseBrackets: true,
  matchTags: { bothTags: true },
  styleActiveLine: true,
  styleSelectedText: true,
  lint: true,
  lintOnChange: true,
};
