name: Master Deployment CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Installing Packages
      run: npm ci
    - name: Deploying to GitHub Pages
      run: |
        git config --global user.email ${{secrets.ADMIN_EMAIL}}
        git config --global user.name ${{secrets.ADMIN_USERNAME}}
        git remote set-url origin https://${{secrets.ADMIN_PERSONAL_ACCESS_TOKEN}}@github.com/${{secrets.ADMIN_USERNAME}}/onsquarecode-ui.git
        npm run deploy
